<message message-id="cacf744a-eca5-46ce-b2a3-80b4a8642cba@u16g2000pru.googlegroups.com" list="com.googlegroups.web2py" id="24cissqq5h22cshc" type="general" date="2009-08-07T20:16:44-07:00" year="2009-01-01" year-month="2009-08-01" year-month-day="2009-08-07" thread-id="meouytocpzkqdigm"><headers><envelope-from-line>Fri Aug 07 20:39:55 2009</envelope-from-line><from personal="jayvandal" address="&quot;jayvan...&quot;@gmail.com">jayvandal &lt;"jayvan..."@gmail.com&gt;</from><to personal="web2py-users" address="web2py@googlegroups.com">web2py-users &lt;web2py@googlegroups.com&gt;</to><subject normal="Images page 60 list index out of range">Re: Images page 60 list index out of range</subject><received>from srv-117c-be06.markmail.marklogic.com ([172.19.8.46])
          by mail-1.a.markmail.int (JAMES SMTP Server 2.3.1) with SMTP ID 461
          for &lt;aline.hamilton.gay@a.markmail.org&gt;;
          Fri, 7 Aug 2009 20:39:54 -0800 (GMT-08:00)</received><received>from crawl-1.a.markmail.int (slb-117n.markmail.marklogic.com [172.19.8.33])
	by mgw-1.public.markmail.int (Postfix) with ESMTP id A08FD2908065
	for &lt;aline.hamilton.gay@a.markmail.org&gt;; Fri,  7 Aug 2009 21:39:31 -0700 (PDT)</received><received>from crawl-1.a.markmail.int (localhost.localdomain [127.0.0.1])
	by crawl-1.a.markmail.int (Postfix) with ESMTP id 7DAD563B0155
	for &lt;aline.hamilton.gay@a.markmail.org&gt;; Fri,  7 Aug 2009 21:39:31 -0700 (PDT)</received><received>(from crawler@localhost)
	by crawl-1.a.markmail.int (8.13.8/8.13.8/Submit) id n784dVkW030002
	for aline.hamilton.gay@a.markmail.org; Fri, 7 Aug 2009 21:39:31 -0700</received><x-authentication-warning>crawl-1.a.markmail.int: crawler set sender to root@localhost using -r</x-authentication-warning><x-markmail-googlegroups-list>com.googlegroups.web2py</x-markmail-googlegroups-list><x-markmail-googlegroups-mid>4d84b0f2cd66e99b</x-markmail-googlegroups-mid><mime-version>1.0</mime-version><received>by 10.151.79.3 with SMTP id g3mr489938ybl.6.1249701404425; Fri, 07 
	Aug 2009 20:16:44 -0700 (PDT)</received><date>Fri, 7 Aug 2009 20:16:44 -0700 (PDT)</date><in-reply-to>&lt;55db87f4-faec-409a-b068-27e86890838a@i4g2000prm.googlegroups.com&gt;</in-reply-to><x-ip>69.20.160.69</x-ip><references>&lt;d5b0ca76-4229-48d5-ba49-8eca0afd1c98@x6g2000prc.googlegroups.com&gt; 
	&lt;24433c3c0908062307x1e0d4e48qd76c2cd45eef40a2@mail.gmail.com&gt; 
	&lt;55db87f4-faec-409a-b068-27e86890838a@i4g2000prm.googlegroups.com&gt;</references><user-agent>G2/1.0</user-agent><x-http-useragent>Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; 
	Trident/4.0; FunWebProducts; GTB6; Mozilla/4.0 (compatible; MSIE 6.0; Windows 
	NT 5.1; SV1) ; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 
	3.0.30618),gzip(gfe),gzip(gfe)</x-http-useragent><message-id>cacf744a-eca5-46ce-b2a3-80b4a8642cba@u16g2000pru.googlegroups.com</message-id><content-type>text/plain; charset=windows-1252</content-type><content-transfer-encoding>quoted-printable</content-transfer-encoding></headers><normalized-references><normalized-message-id>cacf744a-eca5-46ce-b2a3-80b4a8642cba@u16g2000pru.googlegroups.com</normalized-message-id><normalized-in-reply-to>55db87f4-faec-409a-b068-27e86890838a@i4g2000prm.googlegroups.com</normalized-in-reply-to><normalized-reference>d5b0ca76-4229-48d5-ba49-8eca0afd1c98@x6g2000prc.googlegroups.com</normalized-reference><normalized-reference>24433c3c0908062307x1e0d4e48qd76c2cd45eef40a2@mail.gmail.com</normalized-reference><normalized-reference>55db87f4-faec-409a-b068-27e86890838a@i4g2000prm.googlegroups.com</normalized-reference></normalized-references><body type="text/plain; charset=windows-1252"><para depth="0">I have been checking the code.It seemed to bethe first record. Ihad
trouble trying to delete one record so ii DELETED THE DATABASE ising
the delete  of default db. I reintered the database description  and
entered two records. I deleted the  then tried to enter the comment
records. I tried the update and go the IMAGE did not exist. I looked
ate the SQL logand saw there were two instances of image and comment.
Is that what is susposed to be?
Thanks
Jim

</para><footer type="signature" depth="0" hash="11740931523922408024">On Aug 7, 12:54 pm, jayvandal &lt;<email>jayvan...@gmail.com</email>&gt; wrote:
</footer><quote depth="1"><quotepara depth="1">Hi,
I tried your code an I got the same error. It pointed to the first
line of your code gave the same error ,
I guess the first record is 0 so the code is pointing to the first
record?
Thanks for your help
Jim
Error ticket for "images"
Ticket
127.0.0.1.2009-08-07.11-47-01.0a2ffb3a-0bf3-4565-88e2-6c2c572178d0

</quotepara><quotepara depth="1">Error traceback
1.2.3.4.5.6.7. Traceback (most recent call last):  File "gluon/
restricted.py", line 178, in restricted  File "C:/web2py_win(2)/web2py/
applications/images/controllers/default.py", line 24, in &lt;module&gt;
File "gluon/globals.py", line 101, in &lt;lambda&gt;  File "C:/web2py_win(2)/
web2py/applications/images/controllers/default.py", line 6, in
showIndexError: list index out of range

</quotepara><quotepara depth="1">In file: C:\web2py_win(2)\web2py\applications\images/controllers/
default.py
1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25. def
index(): images=db().select(db.image.ALL,orderby=db.image.title)
return dict(images=images) def show(): images = db(db.image.id ==
request.args[1]).select()  if len(images) &lt; 1:    session.flash = T
('No images to show!')    image = images[0]  return dict()  image=db
(db.image.id==request.args[0]).select()[0] form=SQLFORM
(db.comment,fields=['author','email','body'])
form.vars.image_id=image.id if form.accepts(request.vars,session):
response.flash='your comment is posted' comments=db
(db.comment.image_id==image.id).select() return dict
(image=image,comments=comments,form=form)  def
==============================================
This is the images files showing two  records.
======================================
customize me!
/images/default/index
Authentication
LoginRegisterLost PasswordMain Menu
IndexEdit This App
EditControllerViewLayoutStylesheetDB ModelMenu ModelDatabase
 images : image.id image.title image.file
2 me and me file
1 me and the shark file

</quotepara><quotepara depth="1">Current Images
•me and me
•me and the shark

</quotepara><quotepara depth="1">On Aug 7, 12:07 am, Yarko Tymciurak &lt;<email>yark...@gmail.com</email>&gt; wrote:

</quotepara><quote depth="2"><quotepara depth="2">did you create an image with the admin interface, as shown on p. 56?
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">If you did not, then the select on line 6 would return NO records, and
therefore select()[0] would create an
index out of range.
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">You can check / change this by re-writing the select in the show() procedure
to something like this (I have not tried, so it might not be quite right):
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">def show():
    images = db(db.image.id == request.args[0]).select()
    if len(images) &lt; 1:
       session.flash = T('No images to show!')
       return dict()
    image = images[0]
    # the rest as is....
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">Regards,
- Yarko
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">On Fri, Aug 7, 2009 at 12:54 AM,jayvandal&lt;<email>jayvan...@gmail.com</email>&gt; wrote:
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quote depth="3"><quotepara depth="3">Error ticket for "images"
Ticket 127.0.0.1.2009-08-06.23-39-06.cf3dcbd3-ce73-4175-8d61-
ff5aca00c066
</quotepara></quote></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quote depth="3"><quotepara depth="3">Hello,
I am reworking the tutorials in the web2py manual. In this Images
3.6 , I am following the  code and I am lost atthis point.
Thanks for any help
Jim
</quotepara></quote></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quote depth="3"><quotepara depth="3">Error traceback
1.2.3.4.5.6.7. Traceback (most recent call last):  File "gluon/
restricted.py", line 178, in restricted  File "C:/web2py_win(2)/web2py/
applications/images/controllers/default.py", line 19, in &lt;module&gt;
File "gluon/globals.py", line 101, in &lt;lambda&gt;  File "C:/web2py_win(2)/
web2py/applications/images/controllers/default.py", line 6, in
showIndexError: list index out of range
</quotepara></quote></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quote depth="3"><quotepara depth="3">In file: C:\web2py_win(2)\web2py\applications\images/controllers/
default.py
1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20. def index():
images=db().select(db.image.ALL,orderby=db.image.title) return dict
(images=images) def show(): image=db(db.image.id==request.args
[0]).select()[0] form=SQLFORM(db.comment,fields=
['author','email','body']) form.vars.image_id=image.id if form.accepts
(request.vars,session):   response.flash='your comment is posted'
comments=db(db.comment.image_id==image.id).select() return dict
(image=image,comments=comments,form=form)  def download(): import os
path=os.path.join(request.folder,'uploads',request.args[0]) return
response.stream(path)response._vars=response._caller(show)- Hide quoted text -
</quotepara></quote></quote><quotefooter type="noise" depth="1">
</quotefooter><quote depth="2"><quotepara depth="2">- Show quoted text -- Hide quoted text -
</quotepara></quote><quotefooter type="noise" depth="1">
</quotefooter></quote></body></message>